export type ConverterEntry = {
  slug: string
  title: string
  description: string
  href: string
  category: string
}

export const ALL_CONVERTERS: ConverterEntry[] = [
  // Længde
  {
    slug: "fod-til-meter",
    title: "Fod til meter",
    description: "Omregn fod til meter hurtigt og nemt.",
    href: "/laengde/fod-til-meter",
    category: "laengde",
  },
  {
    slug: "meter-til-fod",
    title: "Meter til fod",
    description: "Omregn meter til fod hurtigt og nemt.",
    href: "/laengde/meter-til-fod",
    category: "laengde",
  },
  {
    slug: "hoejde-omregner",
    title: "Højde omregner",
    description: "Omregn højde fra fod og tommer til cm hurtigt og nemt.",
    href: "/laengde/hoejde-omregner",
    category: "laengde",
  },
  {
    slug: "tommer-til-cm",
    title: "Tommer til cm",
    description: "Omregn tommer (inch) til cm hurtigt og nemt.",
    href: "/laengde/tommer-til-cm",
    category: "laengde",
  },
  {
    slug: "cm-til-tommer",
    title: "Cm til tommer",
    description: "Omregn cm til tommer (inch) hurtigt og nemt.",
    href: "/laengde/cm-til-tommer",
    category: "laengde",
  },
  {
    slug: "tommer-til-mm",
    title: "Tommer til mm",
    description: "Omregn tommer til mm hurtigt og nemt.",
    href: "/laengde/tommer-til-mm",
    category: "laengde",
  },
  {
    slug: "mm-til-tommer",
    title: "Mm til tommer",
    description: "Omregn mm til tommer hurtigt og nemt.",
    href: "/laengde/mm-til-tommer",
    category: "laengde",
  },
  {
    slug: "meter-til-cm",
    title: "Meter til cm",
    description: "Omregn meter til cm hurtigt og nemt.",
    href: "/laengde/meter-til-cm",
    category: "laengde",
  },
  {
    slug: "cm-til-m",
    title: "Cm til meter",
    description: "Omregn cm til meter hurtigt og nemt.",
    href: "/laengde/cm-til-m",
    category: "laengde",
  },
  {
    slug: "miles-til-km",
    title: "Miles til km",
    description: "Omregn miles til km hurtigt og nemt.",
    href: "/laengde/miles-til-km",
    category: "laengde",
  },
  {
    slug: "km-til-miles",
    title: "Km til miles",
    description: "Omregn km til miles hurtigt og nemt.",
    href: "/laengde/km-til-miles",
    category: "laengde",
  },
  {
    slug: "soemil-til-km",
    title: "Sømil til km",
    description: "Omregn sømil til km hurtigt og nemt.",
    href: "/laengde/soemil-til-km",
    category: "laengde",
  },
  {
    slug: "yard-til-meter",
    title: "Yard til meter",
    description: "Omregn yard til meter hurtigt og nemt.",
    href: "/laengde/yard-til-meter",
    category: "laengde",
  },
  {
    slug: "meter-til-yard",
    title: "Meter til yard",
    description: "Omregn meter til yard hurtigt og nemt.",
    href: "/laengde/meter-til-yard",
    category: "laengde",
  },
  {
    slug: "mm-til-m",
    title: "Mm til meter",
    description: "Omregn mm til meter hurtigt og nemt.",
    href: "/laengde/mm-til-m",
    category: "laengde",
  },
  {
    slug: "m-til-mm",
    title: "Meter til mm",
    description: "Omregn meter til mm hurtigt og nemt.",
    href: "/laengde/m-til-mm",
    category: "laengde",
  },
  {
    slug: "mm-til-cm",
    title: "Mm til cm",
    description: "Omregn mm til cm hurtigt og nemt.",
    href: "/laengde/mm-til-cm",
    category: "laengde",
  },
  {
    slug: "cm-til-mm",
    title: "Cm til mm",
    description: "Omregn cm til mm hurtigt og nemt.",
    href: "/laengde/cm-til-mm",
    category: "laengde",
  },

  // Vægt
  {
    slug: "pund-til-kg",
    title: "Pund til kg",
    description: "Omregn pund (lbs) til kg hurtigt og nemt.",
    href: "/vaegt/pund-til-kg",
    category: "vaegt",
  },
  {
    slug: "kg-til-lbs",
    title: "Kg til pund",
    description: "Omregn kg til pund (lbs) hurtigt og nemt.",
    href: "/vaegt/kg-til-lbs",
    category: "vaegt",
  },
  {
    slug: "kg-til-gram",
    title: "Kg til gram",
    description: "Omregn kg til gram hurtigt og nemt.",
    href: "/vaegt/kg-til-gram",
    category: "vaegt",
  },
  {
    slug: "gram-til-kg",
    title: "Gram til kg",
    description: "Omregn gram til kg hurtigt og nemt.",
    href: "/vaegt/gram-til-kg",
    category: "vaegt",
  },

  // Temperatur
  {
    slug: "fahrenheit-til-celsius",
    title: "Fahrenheit til celsius",
    description: "Omregn fahrenheit til celsius hurtigt og nemt.",
    href: "/temperatur/fahrenheit-til-celsius",
    category: "temperatur",
  },
  {
    slug: "celsius-til-fahrenheit",
    title: "Celsius til fahrenheit",
    description: "Omregn celsius til fahrenheit hurtigt og nemt.",
    href: "/temperatur/celsius-til-fahrenheit",
    category: "temperatur",
  },

  // Areal
  {
    slug: "hektar-til-m2",
    title: "Hektar til m²",
    description: "Omregn hektar til kvadratmeter hurtigt og nemt.",
    href: "/areal/hektar-til-m2",
    category: "areal",
  },
  {
    slug: "m2-til-hektar",
    title: "m² til hektar",
    description: "Omregn kvadratmeter til hektar hurtigt og nemt.",
    href: "/areal/m2-til-hektar",
    category: "areal",
  },
  {
    slug: "hektar-til-km2",
    title: "Hektar til km²",
    description: "Omregn hektar til kvadratkilometer hurtigt og nemt.",
    href: "/areal/hektar-til-km2",
    category: "areal",
  },
  {
    slug: "hektar-til-tonder",
    title: "Hektar til tønder land",
    description: "Omregn hektar til tønder land hurtigt og nemt.",
    href: "/areal/hektar-til-tonder",
    category: "areal",
  },
  {
    slug: "km2-til-hektar",
    title: "km² til hektar",
    description: "Omregn kvadratkilometer til hektar hurtigt og nemt.",
    href: "/areal/km2-til-hektar",
    category: "areal",
  },
  {
    slug: "tonder-til-hektar",
    title: "Tønder land til hektar",
    description: "Omregn tønder land til hektar hurtigt og nemt.",
    href: "/areal/tonder-til-hektar",
    category: "areal",
  },

  // Hastighed
  {
    slug: "knob-til-km-t",
    title: "Knob til km/t",
    description: "Omregn knob til km/t hurtigt og nemt.",
    href: "/hastighed/knob-til-km-t",
    category: "hastighed",
  },
  {
    slug: "km-t-til-knob",
    title: "Km/t til knob",
    description: "Omregn km/t til knob hurtigt og nemt.",
    href: "/hastighed/km-t-til-knob",
    category: "hastighed",
  },
  {
    slug: "km-t-til-ms",
    title: "Km/t til m/s",
    description: "Omregn km/t til m/s hurtigt og nemt.",
    href: "/hastighed/km-t-til-ms",
    category: "hastighed",
  },
  {
    slug: "ms-til-km-t",
    title: "M/s til km/t",
    description: "Omregn m/s til km/t hurtigt og nemt.",
    href: "/hastighed/ms-til-km-t",
    category: "hastighed",
  },
  {
    slug: "mph-til-km-t",
    title: "Mph til km/t",
    description: "Omregn mph til km/t hurtigt og nemt.",
    href: "/hastighed/mph-til-km-t",
    category: "hastighed",
  },
  {
    slug: "km-t-til-mph",
    title: "Km/t til mph",
    description: "Omregn km/t til mph hurtigt og nemt.",
    href: "/hastighed/km-t-til-mph",
    category: "hastighed",
  },

  // Volumen
  {
    slug: "ml-til-dl",
    title: "Ml til dl",
    description: "Omregn ml til dl hurtigt og nemt.",
    href: "/volumen/ml-til-dl",
    category: "volumen",
  },
  {
    slug: "dl-til-ml",
    title: "Dl til ml",
    description: "Omregn dl til ml hurtigt og nemt.",
    href: "/volumen/dl-til-ml",
    category: "volumen",
  },
  {
    slug: "ml-til-l",
    title: "Ml til liter",
    description: "Omregn ml til liter hurtigt og nemt.",
    href: "/volumen/ml-til-l",
    category: "volumen",
  },
  {
    slug: "l-til-ml",
    title: "Liter til ml",
    description: "Omregn liter til ml hurtigt og nemt.",
    href: "/volumen/l-til-ml",
    category: "volumen",
  },
  {
    slug: "cl-til-dl",
    title: "Cl til dl",
    description: "Omregn cl til dl hurtigt og nemt.",
    href: "/volumen/cl-til-dl",
    category: "volumen",
  },
  {
    slug: "dl-til-cl",
    title: "Dl til cl",
    description: "Omregn dl til cl hurtigt og nemt.",
    href: "/volumen/dl-til-cl",
    category: "volumen",
  },
  {
    slug: "cl-til-ml",
    title: "Cl til ml",
    description: "Omregn cl til ml hurtigt og nemt.",
    href: "/volumen/cl-til-ml",
    category: "volumen",
  },
  {
    slug: "ml-til-cl",
    title: "Ml til cl",
    description: "Omregn ml til cl hurtigt og nemt.",
    href: "/volumen/ml-til-cl",
    category: "volumen",
  },
  {
    slug: "cl-til-l",
    title: "Cl til liter",
    description: "Omregn cl til liter hurtigt og nemt.",
    href: "/volumen/cl-til-l",
    category: "volumen",
  },
  {
    slug: "l-til-cl",
    title: "Liter til cl",
    description: "Omregn liter til cl hurtigt og nemt.",
    href: "/volumen/l-til-cl",
    category: "volumen",
  },
  {
    slug: "dl-til-l",
    title: "Dl til liter",
    description: "Omregn dl til liter hurtigt og nemt.",
    href: "/volumen/dl-til-l",
    category: "volumen",
  },
  {
    slug: "l-til-dl",
    title: "Liter til dl",
    description: "Omregn liter til dl hurtigt og nemt.",
    href: "/volumen/l-til-dl",
    category: "volumen",
  },

  // Tryk
  {
    slug: "psi-til-bar",
    title: "Psi til bar",
    description: "Omregn psi til bar hurtigt og nemt.",
    href: "/tryk/psi-til-bar",
    category: "tryk",
  },
  {
    slug: "bar-til-psi",
    title: "Bar til psi",
    description: "Omregn bar til psi hurtigt og nemt.",
    href: "/tryk/bar-til-psi",
    category: "tryk",
  },
  {
    slug: "kpa-til-bar",
    title: "Kpa til bar",
    description: "Omregn kpa til bar hurtigt og nemt.",
    href: "/tryk/kpa-til-bar",
    category: "tryk",
  },
  {
    slug: "bar-til-kpa",
    title: "Bar til kpa",
    description: "Omregn bar til kpa hurtigt og nemt.",
    href: "/tryk/bar-til-kpa",
    category: "tryk",
  },
]
